name: cicd

on:
  workflow-dispatch:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/main/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ivanjx/frigate:latest
          cache-from: type=registry,ref=ghcr.io/ivanjx/frigate:latest
          cache-to: type=inline
